spring.application.name=school

spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=Peifei02

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


jwt.secret=asduighidsomkfldsnam8y8935y3i2hjlkem9sdafjds$!#%^@))(


jwt.expiration-ms=900000
jwt.refresh-expiration-ms=604800000

